initial commit
Full-Moon-Castle/wizard pull request #1
Opened 2020-03-23 00:00 UTC by cesarmacedo

[Tela de login](https://trello.com/c/DHTVYdI4/7-tela-de-login)

2020-03-25 23:32 UTC, VitorDaynno requested changes

2020-03-25 23:32 UTC, VitorDaynno commented on wizard/app.json
> +  "displayName": "wizard"
Gentileza utilizar o nome do app real

2020-03-25 23:32 UTC, VitorDaynno commented on wizard/src/components/login.js
> +import React, {Component} from 'react';
Utilizar espaços após chaves.

2020-03-25 23:32 UTC, VitorDaynno commented on wizard/src/components/login.js
> +    this.setState({username});
Por que não setar os dois elementos na mesma linha, e por que não setar o error como _null_?

2020-03-25 23:32 UTC, VitorDaynno commented on wizard/src/components/login.js
> +    this.setState({password});
Por que não setar os dois elementos na mesma linha, e por que não setar o error como null?

2020-03-25 23:32 UTC, VitorDaynno commented on wizard/src/components/login.js
> +        {error: 'Preencha todos os campos para continuar!'},
Utilizar espaços após chaves.

2020-03-26 00:36 UTC, cesarmacedo commented on wizard/app.json
> +  "displayName": "wizard"
Corrigido

2020-03-26 00:36 UTC, cesarmacedo commented on wizard/src/components/login.js
> +import React, {Component} from 'react';
Corrigido

2020-03-26 00:38 UTC, cesarmacedo commented on wizard/src/components/login.js
> +    this.setState({username});
Corrigido
não setei como nulo por que  a variável não e logica é string

2020-03-26 00:39 UTC, cesarmacedo commented on wizard/src/components/login.js
> +    this.setState({password});
Corrigido

2020-03-26 00:40 UTC, cesarmacedo commented on wizard/src/components/login.js
> +        {error: 'Preencha todos os campos para continuar!'},
eslint do react-native reclama se colocar espaço

2020-03-26 00:49 UTC, VitorDaynno commented on wizard/app.json
> +  "displayName": "wizard"
Obrigado!

2020-03-26 00:54 UTC, VitorDaynno commented on wizard/src/components/login.js
> +        {error: 'Preencha todos os campos para continuar!'},
OK!

2020-03-26 03:10 UTC, VitorDaynno approved these changes

2020-03-26 03:13 UTC, merged