code correction empty fields validation
Full-Moon-Castle/wizard pull request #6
Opened 2020-04-08 00:38 UTC by cesarmacedo

2020-04-10 23:00 UTC, VitorDaynno requested changes

2020-04-10 23:00 UTC, VitorDaynno commented on src/components/signUp.js
> +    email = email.replace(/\s/g, '');
Por que não utilizar trim() aqui também?

2020-04-10 23:00 UTC, VitorDaynno commented on src/components/signUp.js
> +    password = password.replace(/\s/g, '');
Por que não utilizar trim() aqui também?

2020-04-11 13:50 UTC, cesarmacedo commented on src/components/signUp.js
> +    email = email.replace(/\s/g, '');
Se eu utilizar o trim caso a pessoa consiga inserir espaço o e-mail dela sera cadastrado sem espaço a informação inserida não será mesma cadastrada.
por isso inserir esta regra que impede de utilizar espaço.
password = password.replace(/\s/g, '');

2020-04-11 13:50 UTC, cesarmacedo commented on src/components/signUp.js
> +    password = password.replace(/\s/g, '');
Se eu utilizar o trim caso a pessoa consiga inserir espaço o e-mail dela sera cadastrado sem espaço a informação inserida não será mesma cadastrada.
por isso inserir esta regra que impede de utilizar espaço.
password = password.replace(/\s/g, '');

2020-04-12 01:11 UTC, VitorDaynno commented on src/components/signUp.js
> +    email = email.replace(/\s/g, '');
Qual seria o problema de inserir um email sem espaço?

2020-04-12 01:12 UTC, VitorDaynno commented on src/components/signUp.js
> +    password = password.replace(/\s/g, '');
Essa regra impossibilita que a pessoa utilize espaço no meio da senha como caracter especial

2020-04-12 02:52 UTC, cesarmacedo commented on src/components/signUp.js
> +    password = password.replace(/\s/g, '');
somente espaço em branco

2020-04-12 02:53 UTC, cesarmacedo commented on src/components/signUp.js
> +    email = email.replace(/\s/g, '');
essa regra impossibilita de inserir email com espaço em branco

2020-04-12 03:07 UTC, VitorDaynno approved these changes

2020-04-12 03:13 UTC, merged